apiVersion: v1
kind: Pod
metadata:
  name: webpod
  labels:
    env: test
    dc: IN

spec:
  containers:
  - name: "mywebcont"
    image: "httpd"
    volumeMounts:
     - name: web-vol1
       mountPath:  /usr/local/apache2/htdocs
  volumes:
  - name: web-vol1
    persistentVolumeClaim:
      claimName: webpvc
     
